ProjectCinema/Controllers/SaloonController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectCinema.Data.Models;
using ProjectCinema.Repositories;
using System;
using System.Linq;

namespace ProjectCinema.Controllers
{
    public class SaloonController : Controller
    {
        SaloonRepository saloonRepository = new SaloonRepository();
        ChairRepository chairRepository = new ChairRepository();
        Context c = new Context();
        public IActionResult Index()
        {
            return View(saloonRepository.TList());
        }
        [HttpGet]
        public IActionResult AddSaloon()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSaloon(Saloon s)
        {
            c.Saloons.Add(s);
            c.SaveChanges();
            int id = s.SaloonID;
            for (int i = 0; i < s.LineArmChairNumber; i++)
            {

                for (int j = 0; j < s.ColumnArmChairNumber; j++)
                {
                    var chair = new Chair(); 
                    chair.Status = true;
                    chair.SaloonID = id;
                    c.Chairs.Add(chair);
                    c.SaveChanges();
                }
             }
            return RedirectToAction("Index");
        }
        public IActionResult RemoveSaloon(int id)
        {
            saloonRepository.TRemove(new Saloon { SaloonID = id });
            return RedirectToAction("Index");
        }
        public IActionResult GetSaloon(int id)
        {
            var x = saloonRepository.GetT(id);
            return View("GetSaloon", x);
        }
        public IActionResult UpdateSaloon(Saloon s)
        {
            saloonRepository.TUpdate(s);
            return RedirectToAction("Index");
        }
    }
}

ProjectCinema/Views/Saloon/AddSaloon.cshtml
@model ProjectCinema.Data.Models.Saloon
@{
    ViewData["Title"] = "AddSaloon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddSaloon", "Saloon", FormMethod.Post))
{
    @Html.LabelFor(x => x.SaloonName)
    @Html.TextBoxFor(x => x.SaloonName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.LineArmChairNumber)
    @Html.TextBoxFor(x => x.LineArmChairNumber, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ColumnArmChairNumber)
    @Html.TextBoxFor(x => x.ColumnArmChairNumber, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">SAVE</button>
}

ProjectCinema/Views/Saloon/GetSaloon.cshtml
@model ProjectCinema.Data.Models.Saloon
@{
    ViewData["Title"] = "GetSaloon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("UpdateSaloon", "Saloon", FormMethod.Post))
{
    @Html.LabelFor(x => x.SaloonID)
    @Html.TextBoxFor(x => x.SaloonID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.SaloonName)
    @Html.TextBoxFor(x => x.SaloonName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.LineArmChairNumber)
    @Html.TextBoxFor(x => x.LineArmChairNumber, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ColumnArmChairNumber)
    @Html.TextBoxFor(x => x.ColumnArmChairNumber, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Update</button>
}

ProjectCinema/Views/Saloon/Index.cshtml
@model List<ProjectCinema.Data.Models.Saloon>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h1 align="center">Saloon List</h1>
<br />
<table class="table table-bordered">
    <tr align="center">
        <th>ID</th>
        <th>Saloon</th>
        <th>Line ArmChair Number</th>
        <th>Column ArmChair Number</th>
        <th>Delete</th>
        <th>Update</th>
        <th>Show Saloon</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr align="center">
            <td>@x.SaloonID</td>
            <td>@x.SaloonName</td>
            <td>@x.LineArmChairNumber</td>
            <td>@x.ColumnArmChairNumber</td>
            <td><a href="/Saloon/RemoveSaloon/@x.SaloonID" class="btn btn-danger">Delete</a></td>
            <td><a href="/Saloon/GetSaloon/@x.SaloonID" class="btn btn-success">Update</a></td>
            <td><a href="/ButtonClick/GetSaloon3/@x.SaloonID" class="btn btn-success">Show Saloon</a></td>
        </tr>
    }

</table>
<a href="/Saloon/AddSaloon/" class="btn btn-primary">New Saloon</a>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />