ProjectCinema/Controllers/SessionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectCinema.Data.Models;
using ProjectCinema.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectCinema.Controllers
{
    public class SessionController : Controller
    {
        Context c = new Context();
        SessionRepository sessionRepository = new SessionRepository();
        public IActionResult Index()
        {
            sessionRepository.TList("Movie");
            return View(sessionRepository.TList("Saloon"));
        }
        [HttpGet]
        public IActionResult AddSession()
        {
            List<SelectListItem> value = (from x in c.Saloons.ToList()  
                                          select new SelectListItem
                                          {
                                              Text = x.SaloonName,
                                              Value = x.SaloonID.ToString()
                                          }).ToList();
            List<SelectListItem> value2 = (from y in c.Movies.ToList()
                                          select new SelectListItem
                                          {
                                              Text = y.MovieName,
                                              Value = y.MovieID.ToString()
                                          }).ToList();
            ViewBag.v1 = value;
            ViewBag.v2 = value2;
            //var Mov = new List<MovieCategory> { };
            //ViewBag.Mov =  new SelectList(Mov, "SessionID", "Time", "SaloonID", "MovieCategoryID");
            return View();
        }
        [HttpPost]
        public IActionResult AddSession(Session s)
        {
            sessionRepository.TAdd(s);
            return RedirectToAction("Index");
        }
        public IActionResult RemoveSession(int id)
        {
            sessionRepository.TRemove(new Session { SessionID = id });
            return RedirectToAction("Index");
        }
        public IActionResult GetSession(int id)
        {
            List<SelectListItem> value = (from y in c.Saloons.ToList()
                                          select new SelectListItem
                                          {
                                              Text = y.SaloonName,
                                              Value = y.SaloonID.ToString()
                                          }).ToList();
            List<SelectListItem> value2 = (from z in c.Movies.ToList()
                                           select new SelectListItem
                                           {
                                               Text = z.MovieName,
                                               Value = z.MovieID.ToString()
                                           }).ToList();
            ViewBag.v2 = value2;
            ViewBag.v1 = value;
            var x = sessionRepository.GetT(id);
            return View("GetSession", x);
        }
        public IActionResult UpdateSession(Session s)
        {
            sessionRepository.TUpdate(s);
            return RedirectToAction("Index");
        }
    }
}

ProjectCinema/Views/Session/AddSession.cshtml
@model ProjectCinema.Data.Models.Session
@{
    ViewData["Title"] = "AddSession";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddSession", "Session", FormMethod.Post))
{
    @Html.LabelFor(x => x.Time)
    @Html.TextBoxFor(x => x.Time, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Saloon)
    @Html.DropDownListFor(x => x.SaloonID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control " })
    <br />
    @Html.LabelFor(x => x.Movie)
    @Html.DropDownListFor(x => x.MovieID, (List<SelectListItem>)ViewBag.v2, new { @class = "form-control " })
    //@Html.DropDownList("Mov", "Lütfen bir öğrenci seçiniz...")
    <br />
    <button class="btn btn-info">SAVE</button>
}

ProjectCinema/Views/Session/GetSession.cshtml
@model ProjectCinema.Data.Models.Session
@{
    ViewData["Title"] = "GetSession";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("UpdateSession", "Session", FormMethod.Post))
{
    @Html.LabelFor(x => x.SessionID)
    @Html.TextBoxFor(x => x.SessionID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Time)
    @Html.TextBoxFor(x => x.Time, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Saloon)
    @Html.DropDownListFor(x => x.SaloonID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control " })
    <br />
    @Html.LabelFor(x => x.Movie)
    @Html.DropDownListFor(x => x.MovieID, (List<SelectListItem>)ViewBag.v2, new { @class = "form-control " })
    <br />
    <button class="btn btn-info">Update</button>
}

ProjectCinema/Views/Session/Index.cshtml
  @model List<ProjectCinema.Data.Models.Session>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />
<h1 align="center">Session List</h1>
<br />
<table class="table table-bordered">
    <tr align="center">
        <th>ID</th>
        <th>Session</th>
        <th>Saloon</th>
        <th>Movie</th>
        <th>Delete</th>
        <th>Update</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr align="center">
            <td>@x.SessionID</td>
            <td>@x.Time</td>
            <td>@x.Saloon.SaloonName</td>
            <td>@x.Movie.MovieName</td>
            <td><a href="/Session/RemoveSession/@x.SessionID" class="btn btn-danger">Delete</a></td>
            <td><a href="/Session/GetSession/@x.SessionID" class="btn btn-success">Update</a></td>
        </tr>
    }

</table>
<a href="/Session/AddSession/" class="btn btn-primary">New Session</a>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />