ProjectCinema/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectCinema.Data.Models;
using ProjectCinema.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectCinema.Controllers
{
    public class TicketController : Controller
    {
        TicketRepository ticketRepository = new TicketRepository();
        ChairRepository chairRepository = new ChairRepository();
        SessionRepository sessionRepository = new SessionRepository();
        Context c = new Context();
        public IActionResult Index()
        {
            return View(ticketRepository.TList("Session"));
        }
        [HttpGet]
        public IActionResult AddTicket()
        {
            List<SelectListItem> value = (from x in c.Sessions.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Time,
                                              Value = x.SessionID.ToString()
                                          }).ToList();
            ViewBag.v1 = value;
            return View();
        }
        [HttpPost]
        public IActionResult AddTicket(Ticket s)
        {
            ticketRepository.TAdd(s);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AddTicket2()
        {
            List<SelectListItem> value = (from x in c.Sessions.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Time,
                                              Value = x.SessionID.ToString()
                                          }).ToList();
            ViewBag.v1 = value;
            return View();
        }
        [HttpPost]
        public IActionResult AddTicket2(Ticket s)
        {
            var x = s.SessionID;// SessionID geçici olarak tutuluyor kaydetmiyorum.
            return RedirectToAction("GetSaloon3", new { id = x });
        }
        public IActionResult GetSaloon3(int id)
        {
            ViewBag.v2 = id;
            var salid = c.Sessions.Where(x => x.SessionID == id).Select(y => y.SaloonID).FirstOrDefault();
            var column = c.Saloons.Where(x => x.SaloonID == salid).Select(y => y.ColumnArmChairNumber).FirstOrDefault();
            var line = c.Saloons.Where(x => x.SaloonID == salid).Select(y => y.LineArmChairNumber).FirstOrDefault();
            ViewBag.c1 = line;
            ViewBag.c2 = column;
            int chair = c.Chairs.Where(x => x.SaloonID == salid).OrderBy(z => z.ChairID).Select(y => y.ChairID).FirstOrDefault();
            ViewBag.v1 = chair;
            var values = c.Chairs.Where(x => x.SaloonID == salid).ToList();
            return View("GetSaloon3", values);
        }
        public IActionResult RemoveTicket(int id)
        {
            ticketRepository.TRemove(new Ticket { TicketID = id });
            return RedirectToAction("Index");
        }
        public IActionResult GetTicket(int id)
        {
            List<SelectListItem> value = (from y in c.Sessions.ToList()
                                          select new SelectListItem
                                          {
                                              Text = y.Time,
                                              Value = y.SessionID.ToString()
                                          }).ToList();
            ViewBag.v1 = value;
            var x = ticketRepository.GetT(id); 
            return View("GetTicket", x);
        }
        public IActionResult UpdateTicket(Ticket s)
        {
            ticketRepository.TUpdate(s);
            return RedirectToAction("Index");
        }
        public IActionResult GetSaloon(int id)
        {
            ViewBag.v2 = id;
            var salid = c.Chairs.Where(x => x.ChairID == id).Select(y => y.SaloonID).FirstOrDefault();
            var column = c.Saloons.Where(x => x.SaloonID == salid).Select(y => y.ColumnArmChairNumber).FirstOrDefault();
            var line = c.Saloons.Where(x => x.SaloonID == salid).Select(y => y.LineArmChairNumber).FirstOrDefault();
            ViewBag.c1 = line;
            ViewBag.c2 = column;
            int chair = c.Chairs.Where(x => x.SaloonID == salid).OrderBy(z => z.ChairID).Select(y => y.ChairID).FirstOrDefault();
            ViewBag.v1 = salid;
            var values = c.Chairs.Where(x => x.SaloonID == salid).ToList();
            return View("GetSaloon", values);
        }
    }
}

ProjectCinema/Views/Ticket/AddTicket.cshtml
@model ProjectCinema.Data.Models.Ticket
@{
    ViewData["Title"] = "AddTicket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddTicket", "Ticket", FormMethod.Post))
{
    @Html.LabelFor(x => x.Session)
    @Html.DropDownListFor(x => x.SessionID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control " })
    <br />
    <button class="btn btn-info">SAVE</button>
}

ProjectCinema/Views/Ticket/AddTicket2.cshtml
@model ProjectCinema.Data.Models.Ticket
@{
    ViewData["Title"] = "AddTicket2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddTicket2", "Ticket", FormMethod.Post))
{
    @Html.LabelFor(x => x.Session)
    @Html.DropDownListFor(x => x.SessionID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control " })
    <br />
    <button class="btn btn-info">Next</button>
}

ProjectCinema/Views/Ticket/GetSaloon.cshtml
@model List<ProjectCinema.Data.Models.Chair>
@{
    ViewData["Title"] = "GetSaloon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />

@{
    int satir = ViewBag.c1;
    int sutun = ViewBag.c2;
    int chair = ViewBag.v1;
    int showchair = ViewBag.v2;
    int sayac = 0;
    <div class="response"></div>
    @for (int i = 0; i < satir; i++)
    {
        @for (int j = 1; j <= sutun; j++)
        {
            <button type="submit" name="mine" value=@chair>
                @if (Model[sayac].ChairID == showchair)
                {
                    <img src="~/Images/show.png" />
                }
                else if (Model[sayac].Status == true)
                {
                    <img src="~/Images/on.png" />
                }
                else
                {
                    <img src="~/Images/off.png" />
                }
            </button>
            chair++;
            sayac++;
        }
        <br />
    }
    <br />
    <h1 style="color:black">the chair you purchased is yellow colour.</h1>
    <br />
}

ProjectCinema/Views/Ticket/GetSaloon3.cshtml
@model List<ProjectCinema.Data.Models.Chair>
@{
    ViewData["Title"] = "GetSaloon3";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@{
    int satir = ViewBag.c1;
    int sutun = ViewBag.c2;
    int chair = ViewBag.v1;
    int sayac = 0;
    var SaloonID = (Model[0].SaloonID).ToString();
    var SessionID = ViewBag.v2;
    <div id ="Test"class="@SessionID"></div>
    <h1>Saloon @SaloonID</h1>
    <div class="response"></div>
    @for (int i = 0; i < satir; i++)
    {
        @for (int j = 1; j <= sutun; j++)
        {
            <button type="submit" class="chairButton2 @(Model[sayac].Status == true ? "tChair" : "fChair")" name="mine" value=@chair>
                @if (Model[sayac].Status == true)
                {
                    <img src="~/Images/on.png" />
                }
                else
                {
                    <img src="~/Images/off.png" />
                }
            </button>
            chair++;
            sayac++;
        }
        <br />
    }
}

ProjectCinema/Views/Ticket/GetTicket.cshtml
@model ProjectCinema.Data.Models.Ticket
@{
    ViewData["Title"] = "GetTicket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("UpdateTicket", "Ticket", FormMethod.Post))
{
    @Html.LabelFor(x => x.TicketID)
    @Html.TextBoxFor(x => x.TicketID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Session)
    @Html.DropDownListFor(x => x.SessionID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control " })
    <br />
    <button class="btn btn-info">Update</button>
}

ProjectCinema/Views/Ticket/Index.cshtml
@model List<ProjectCinema.Data.Models.Ticket>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h1 align="center">Ticket List</h1>
<br />
<table class="table table-bordered">
    <tr align="center">
        <th>ID</th>
        <th>Session</th>
        <th>Saloon</th>
        <th>Movie</th>
        <th>Chair</th>
        <th>Delete</th>
        <th>Update</th>
        <th>Show Saloon</th>
    </tr>
    @foreach (var x in Model)
    {
<tr align="center">
    <td>@x.TicketID</td>
    <td>@x.Session.Time</td>
    <td>@x.Session.SaloonID</td>
    <td>@x.Session.MovieID</td>
    <td>@x.ChairID</td>
    <td><a href="/Ticket/RemoveTicket/@x.TicketID" class="btn btn-danger">Delete</a></td>
    <td><a href="/Ticket/GetTicket/@x.TicketID" class="btn btn-success">Update</a></td>
    <td><a href="/Ticket/GetSaloon/@x.ChairID" class="btn btn-success">Show Saloon</a></td>
</tr>
    }

</table>
<a href="/Ticket/AddTicket2/" class="btn btn-primary">New Ticket</a>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />